### ISSUE TITLE
Initialize a project

### ISSUE THREAD

**Issue by spalger** [spalger/atelier#2]
A project is just a config file with a few values to configure Atelier. A basic config file will look something like this:

```yaml
roots:
  - name: kibana
    path: /Users/spalger/dev/kibana
    
  - name: x-pack
    path: /Users/spalger/dev/x-pack/kibana
  
server:
  version: 1
  port: 5050
  staticPaths:
    - path: *:(src/plugins/{pluginName}/public|{pluginName}/public)
      route: /plugin/{pluginName}

transform:
  jsnext:
    version: 1
    sources:
      - *:**/public/**/*.js
    opts:
      decorators: false
      bindOperator: false
      asyncAwait: false

  css:
    version: 1
    sources:
      - *:**/public/**/*.less
    opts:
      includes:
        - *:node_modules/
```
